### ISSUE TITLE
Strange diameter numbers in pupil_position file

### ISSUE THREAD

**Issue by mihaelataranu** [hejtmy/pupilr#5]
Hi, I am very new to using Play Labs and R. I wondered if you ever encountered very large numbers for pupil diameter? Typically, for my dataset they are between 30.00 and 45.00. But sometimes they go to thousands. Could it be a recording error?
Thanks in advance.

**Comment by hejtmy** [comment]
I started using the pupil eyetracker just a month ago and I haven't even played with the diameter metrics up to this point :/ I'll let you know if I stumpble upon something similar ;) 

Just from experince, you can try and check if this happens in particular portions of the recording. For example, if it only happens if the subject is looking in the right upper cordnere, it might be due to how the cameras are positioned and calibrated. Personally, from what I saw in the last month, I am happy with the eyetracker for my needs, but I wouldn't use it for fast recordings (it only goes to 200 HZ) nad probably neigher for pupil size. Fixations seem to be a little wonky as well.
